default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: camera_snapshot_development

test:
  <<: *default
  database: camera_snapshot_test

production:
  <<: *default
  database: camera_snapshot_production
  username: camera_snapshot
  password: <%= ENV['CAMERA_SNAPSHOT_DATABASE_PASSWORD'] %>
